// Package docs GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import (
	"bytes"
	"encoding/json"
	"strings"
	"text/template"

	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/i/{SlugCode}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "get a invite card by SlugCode",
                "operationId": "get-invite-card-by-slugcode",
                "parameters": [
                    {
                        "type": "string",
                        "description": "SlugCode is a string reference code for a created Invite Card",
                        "name": "SlugCode",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.GetInviteCardPayload"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api.GetInviteCardPayload"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.GetInviteCardPayload": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/db.InviteCard"
                },
                "error": {
                    "type": "string"
                }
            }
        },
        "db.BusinessJSON": {
            "type": "object",
            "properties": {
                "corp_phrase": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "logo_image": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "db.ContentJSON": {
            "type": "object",
            "properties": {
                "background_color": {
                    "type": "string"
                },
                "background_image": {
                    "type": "string"
                }
            }
        },
        "db.InviteCard": {
            "type": "object",
            "properties": {
                "business": {
                    "$ref": "#/definitions/db.BusinessJSON"
                },
                "business_id": {
                    "type": "string"
                },
                "content": {
                    "$ref": "#/definitions/db.ContentJSON"
                },
                "id": {
                    "type": "string"
                },
                "social": {
                    "$ref": "#/definitions/db.SocialJSON"
                }
            }
        },
        "db.SocialItem": {
            "type": "object",
            "properties": {
                "back_link": {
                    "type": "string"
                },
                "cover_image": {
                    "type": "string"
                },
                "sub_title": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "db.SocialJSON": {
            "type": "object",
            "properties": {
                "links": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/db.SocialItem"
                    }
                }
            }
        }
    },
    "securityDefinitions": {
        "APIKeyAuth": {
            "type": "apiKey",
            "name": "api-key",
            "in": "header"
        },
        "JWTAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "0.0.1",
	Host:        "www.qrinvitecard.com",
	BasePath:    "/api",
	Schemes:     []string{},
	Title:       "QR Invite Card API",
	Description: "This is the documentation for the QR Invite Card API",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
		"escape": func(v interface{}) string {
			// escape tabs
			str := strings.Replace(v.(string), "\t", "\\t", -1)
			// replace " with \", and if that results in \\", replace that with \\\"
			str = strings.Replace(str, "\"", "\\\"", -1)
			return strings.Replace(str, "\\\\\"", "\\\\\\\"", -1)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register("swagger", &s{})
}
